### ISSUE TITLE
Build failed due to older versions of DeLaGuardo / setup-graalvm

### ISSUE THREAD

**Issue by fahad-israr** [starfixdev/starfix#52]
- Unable to resolve action DeLaGuardo/setup-graalvm@3, unable to find version 3
-  Update to DeLaGuardo/setup-graalvm@4

**Comment by fahad-israr** [comment]
- Though we should update to v4, v3 should also work.
- I've already opened an issue here: https://github.com/DeLaGuardo/setup-graalvm/issues/14
- The maintainer looks pretty active. They've responded affirmatively.

**Comment by DeLaGuardo** [comment]
Sorry for jumping in, but why are you using `DeLaGuardo/setup-graalvm@4` without a minor part of the version? The most recent identifier is `@4.0`. I can't guarantee that identifier `@4` will work because it wasn't ever released like that. The issue you mentioned in the previous message was about `@3`, which I have mentioned in the README for some time, and that's why I replied that I would add a tag.

**Comment by fahad-israr** [comment]
We're using `DeLaGuardo/setup-graalvm@3` .
Did I miss something?

> Sorry for jumping in, but why are you using `DeLaGuardo/setup-graalvm@4` without a minor part of the version? The most recent identifier is `@4.0`. I can't guarantee that identifier `@4` will work because it wasn't ever released like that. The issue you mentioned in the previous message was about `@3`, which I have mentioned in the README for some time, and that's why I replied that I would add a tag.

We're using `DeLaGuardo/setup-graalvm@3` .
Did I miss something?

**Comment by DeLaGuardo** [comment]
This is more a question about your intention to update to `DeLaGuardo/setup-graalvm@4`. You were right about opening an issue about `DeLaGuardo/setup-graalvm@3` because that tag was once added to the repository and deleted a short time after by accident (most likely due to me using the wrong command of git CLI). In general action's version should be something identified as a git reference. It could be a branch name, a commit sha or a tag. Unfortunately, tag `4` wasn't ever published so instead of `DeLaGuardo/setup-graalvm@4` I recommend using `DeLaGuardo/setup-graalvm@4.0` as the most recent published tag.

**Comment by fahad-israr** [comment]
> This is more a question about your intention to update to `DeLaGuardo/setup-graalvm@4`. You were right about opening an issue about `DeLaGuardo/setup-graalvm@3` because that tag was once added to the repository and deleted a short time after by accident (most likely due to me using the wrong command of git CLI). In general action's version should be something identified as a git reference. It could be a branch name, a commit sha or a tag. Unfortunately, tag `4` wasn't ever published so instead of `DeLaGuardo/setup-graalvm@4` I recommend using `DeLaGuardo/setup-graalvm@4.0` as the most recent published tag.

Thanks a lot !!
That's helpful :)

**Comment by fahad-israr** [comment]
Resolved @699030be76480a22a34bfb53bf1e7014a093f7d3
